### PR TITLE
QR code in Readme

### PR DESCRIPTION
**Pull request by haawa799**
In case someone opened this repository not on mobile, Apple's download banner doesn't help much.
Added QR code and moved CI build status to the top of the Readme.

### CODE REVIEW

**Comment by matthewpalmer** [comment]
Nice one! Thanks :+1: 

I'll also do a bit of reformatting on top of this over the next few days (because I wasn't happy with the way I had the README laid out previously).

What's your name/twitter handle/...? I'll add you to the contributors list (and give contributors a mention in release notes)

**Comment by haawa799** [comment]
Don't think it's worth mentioning, but anyway, @haawa799 :smile: 

I was thinking about changing UI to look a bit more fancy. 
Do you have any constraints on how the UI should look? 

I think I will make change to one controller just to show what I mean.

**Comment by matthewpalmer** [comment]
All contributions—big or small—are super valuable for Charter :smile: 

Hmm no major constraints, but UI changes will probably go through a bit more discussion than other changes. Sounds good! Feel free to do a mockup in photoshop or whatever if that's easier

**Comment by matthewpalmer** [comment]
Also just FYI I swapped out the QR code for a short link, keeping in the spirit of this PR :)

**Pull request merged**
