### PR TITLE
Localisation

### PR DESCRIPTION
**Pull request by franciscoamado**
- Localisation files for Portuguese and Spanish
- Localized possible xibs
- String localisation with constants through Localizable.swift
  % Corrected NoThreadsTableViewCell xib to support bigger strings: constraining labels to leading and trailing instead of centring X and giving it max width 
  @matthewpalmer 
  Issue #36

### CODE REVIEW

**Comment by matthewpalmer** [comment]
Awesome work!

Merging this in soon.

Pretty big ask but would you be willing to localise the App Store title, keywords and description as well? The description doesn't need to be as long (or match at all, really—I'm not fussy about it) the English version. I'm happy to fiddle with all the fastlane stuff—just writing a variant of them as a comment on this issue and I'll sort the rest out would be really helpful. No worries if you don't have time—I really appreciate the work already.

What name and URL would you like me to link to in the contributors file and mention in the release notes?

Thanks very much

**Comment by franciscoamado** [comment]
Thanks for the compliment :)

Of course I don't mind giving you a help on localising the App store data. I'll be doing it as soon as I can.
I forgot about the contributions page also xD
You can use my github name and link (FranciscoAmado, https://github.com/FranciscoAmado). Thanks!

I'll let you know when I have it localized!
Francisco

**Comment by franciscoamado** [comment]
Hi,

I've localised the app store metadata to Portuguese.
Just missing the screenshots if you think it's worth localising them.
[localisationAppStore.docx](https://github.com/matthewpalmer/Charter/files/182203/localisationAppStore.docx)

**Comment by matthewpalmer** [comment]
Awesome, thank you!

I think fastlane/snapshot will take care of the screenshots (I swear that thing works like magic haha) :D

**Comment by franciscoamado** [comment]
Never used it, have to give it a try and see the magic

**Pull request merged**
